; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Convert2DTo3D"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "FlashBIM, Inc."
#define MyAppURL "https://flashbim.com/"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{62869C98-5018-40AA-9EAE-6F375FE779D8}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\ProgramData\Autodesk\Revit\Addins\{#MyAppName}
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir=..\OutputSetupAIO
OutputBaseFilename=Convert2DTo3D_Installer_V1.0.0
Compression=lzma
SolidCompression=yes
DisableWelcomePage=False
VersionInfoVersion=1.0.0
WizardResizable=True
UninstallDisplayName=Convert2DTo3D_V1.0.0

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]

Source: "..\bin\Release\2022\*"; DestDir: "C:\ProgramData\Autodesk\Revit\Addins\2022"; Flags: ignoreversion recursesubdirs createallsubdirs; Tasks: Revit2022
Source: "..\bin\Release\2023\*"; DestDir: "C:\ProgramData\Autodesk\Revit\Addins\2023"; Flags: ignoreversion recursesubdirs createallsubdirs; Tasks: Revit2023
Source: "..\bin\Release\2024\*"; DestDir: "C:\ProgramData\Autodesk\Revit\Addins\2024"; Flags: ignoreversion recursesubdirs createallsubdirs; Tasks: Revit2024

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Tasks]

Name: "Revit2022"; Description: "Revit 2022"; GroupDescription: "Please select version for Revit"; Flags: unchecked
Name: "Revit2023"; Description: "Revit 2023"; GroupDescription: "Please select version for Revit"; Flags: unchecked
Name: "Revit2024"; Description: "Revit 2024"; GroupDescription: "Please select version for Revit"; Flags: unchecked


[Dirs]

Name: "C:\ProgramData\Autodesk\Revit\Addins\2022"; Tasks: Revit2022
Name: "C:\ProgramData\Autodesk\Revit\Addins\2023"; Tasks: Revit2023
Name: "C:\ProgramData\Autodesk\Revit\Addins\2024"; Tasks: Revit2024


[Messages]
english.WizardSelectTasks=Installing Convert2DTo3D 2022-2024
