//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convert2DTo3D.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Convert2DTo3D.Properties.Resources_en-US", typeof(Resources_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string GEN_Cancel {
            get {
                return ResourceManager.GetString("GEN_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constance.
        /// </summary>
        internal static string GEN_Constance {
            get {
                return ResourceManager.GetString("GEN_Constance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal.
        /// </summary>
        internal static string GEN_Equal {
            get {
                return ResourceManager.GetString("GEN_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string GEN_Error {
            get {
                return ResourceManager.GetString("GEN_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished!.
        /// </summary>
        internal static string GEN_Finished {
            get {
                return ResourceManager.GetString("GEN_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreaterThan.
        /// </summary>
        internal static string GEN_GreaterThan {
            get {
                return ResourceManager.GetString("GEN_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infomation.
        /// </summary>
        internal static string GEN_Info {
            get {
                return ResourceManager.GetString("GEN_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infomation.
        /// </summary>
        internal static string GEN_Information {
            get {
                return ResourceManager.GetString("GEN_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input value is within the range from {0} to {1}..
        /// </summary>
        internal static string GEN_InputDoubleRange {
            get {
                return ResourceManager.GetString("GEN_InputDoubleRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value must be an double.
        /// </summary>
        internal static string GEN_InputRequireDouble {
            get {
                return ResourceManager.GetString("GEN_InputRequireDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value must be an double and greater than or equal to {0}..
        /// </summary>
        internal static string GEN_InputRequireDoubleAndGreaterEqualValue {
            get {
                return ResourceManager.GetString("GEN_InputRequireDoubleAndGreaterEqualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value must be an double and greater than to {0}..
        /// </summary>
        internal static string GEN_InputRequireDoubleAndGreaterValue {
            get {
                return ResourceManager.GetString("GEN_InputRequireDoubleAndGreaterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value must be an integer..
        /// </summary>
        internal static string GEN_InputRequireInteger {
            get {
                return ResourceManager.GetString("GEN_InputRequireInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value must be an integer and greater than or equal to {0}..
        /// </summary>
        internal static string GEN_InputRequireIntegerAndGreaterEqualValue {
            get {
                return ResourceManager.GetString("GEN_InputRequireIntegerAndGreaterEqualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value must be an integer and greater than to {0}..
        /// </summary>
        internal static string GEN_InputRequireIntegerAndGreaterValue {
            get {
                return ResourceManager.GetString("GEN_InputRequireIntegerAndGreaterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value must not be empty..
        /// </summary>
        internal static string GEN_InputRequireValidation {
            get {
                return ResourceManager.GetString("GEN_InputRequireValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input values are incorrect, please check again..
        /// </summary>
        internal static string GEN_InputValuesIncorrect {
            get {
                return ResourceManager.GetString("GEN_InputValuesIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LessThan.
        /// </summary>
        internal static string GEN_LessThan {
            get {
                return ResourceManager.GetString("GEN_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotConstance.
        /// </summary>
        internal static string GEN_NotConstance {
            get {
                return ResourceManager.GetString("GEN_NotConstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotEqual.
        /// </summary>
        internal static string GEN_NotEqual {
            get {
                return ResourceManager.GetString("GEN_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string GEN_Preview {
            get {
                return ResourceManager.GetString("GEN_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successed!.
        /// </summary>
        internal static string GEN_Success {
            get {
                return ResourceManager.GetString("GEN_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string GEN_Warning {
            get {
                return ResourceManager.GetString("GEN_Warning", resourceCulture);
            }
        }
    }
}
