//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convert2DTo3D.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_ja_JP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ja_JP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Convert2DTo3D.Properties.Resources_ja-JP", typeof(Resources_ja_JP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string GEN_Cancel {
            get {
                return ResourceManager.GetString("GEN_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 含む.
        /// </summary>
        internal static string GEN_Constance {
            get {
                return ResourceManager.GetString("GEN_Constance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等しい.
        /// </summary>
        internal static string GEN_Equal {
            get {
                return ResourceManager.GetString("GEN_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string GEN_Error {
            get {
                return ResourceManager.GetString("GEN_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功しました.
        /// </summary>
        internal static string GEN_Finished {
            get {
                return ResourceManager.GetString("GEN_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to より大きい.
        /// </summary>
        internal static string GEN_GreaterThan {
            get {
                return ResourceManager.GetString("GEN_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        internal static string GEN_Info {
            get {
                return ResourceManager.GetString("GEN_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        internal static string GEN_Information {
            get {
                return ResourceManager.GetString("GEN_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} から {1} までの範囲内で値を入力してください。.
        /// </summary>
        internal static string GEN_InputDoubleRange {
            get {
                return ResourceManager.GetString("GEN_InputDoubleRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力値は倍精度浮動小数点数（double）である必要があります。.
        /// </summary>
        internal static string GEN_InputRequireDouble {
            get {
                return ResourceManager.GetString("GEN_InputRequireDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力値は倍精度浮動小数点数（double）で、かつ {0} 以上である必要があります。.
        /// </summary>
        internal static string GEN_InputRequireDoubleAndGreaterEqualValue {
            get {
                return ResourceManager.GetString("GEN_InputRequireDoubleAndGreaterEqualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力値は倍精度浮動小数点数（double）で、かつ {0} より大きい必要があります。.
        /// </summary>
        internal static string GEN_InputRequireDoubleAndGreaterValue {
            get {
                return ResourceManager.GetString("GEN_InputRequireDoubleAndGreaterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力値は整数で入力してください。.
        /// </summary>
        internal static string GEN_InputRequireInteger {
            get {
                return ResourceManager.GetString("GEN_InputRequireInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力値は整数で、{0} 以上で入力してください。.
        /// </summary>
        internal static string GEN_InputRequireIntegerAndGreaterEqualValue {
            get {
                return ResourceManager.GetString("GEN_InputRequireIntegerAndGreaterEqualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力値は整数であり、{0} より大きい必要があります。.
        /// </summary>
        internal static string GEN_InputRequireIntegerAndGreaterValue {
            get {
                return ResourceManager.GetString("GEN_InputRequireIntegerAndGreaterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力値を入力してください。.
        /// </summary>
        internal static string GEN_InputRequireValidation {
            get {
                return ResourceManager.GetString("GEN_InputRequireValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力値が正しくありません。再度確認してください。.
        /// </summary>
        internal static string GEN_InputValuesIncorrect {
            get {
                return ResourceManager.GetString("GEN_InputValuesIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to より小さい.
        /// </summary>
        internal static string GEN_LessThan {
            get {
                return ResourceManager.GetString("GEN_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 含まない.
        /// </summary>
        internal static string GEN_NotConstance {
            get {
                return ResourceManager.GetString("GEN_NotConstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等しくない.
        /// </summary>
        internal static string GEN_NotEqual {
            get {
                return ResourceManager.GetString("GEN_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 適用.
        /// </summary>
        internal static string GEN_Preview {
            get {
                return ResourceManager.GetString("GEN_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功しました.
        /// </summary>
        internal static string GEN_Success {
            get {
                return ResourceManager.GetString("GEN_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        internal static string GEN_Warning {
            get {
                return ResourceManager.GetString("GEN_Warning", resourceCulture);
            }
        }
    }
}
